---
title: "exploration"
author: "Islam Ali"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(gridExtra)



```

```{r}
flu<-readr::read_csv("flu.csv")
```

```{r}
flu<-flu|>select(WHOREGION,HEMISPHERE,COUNTRY_AREA_TERRITORY,ISO_WEEKSTARTDATE,
                 ISO_YEAR,ISO_WEEK,SPEC_PROCESSED_NB,INF_ALL,
                 INF_NEGATIVE,HUMAN_CORONA,METAPNEUMO,PARAINFLUENZA,RHINO,
                 RSV,INF_A,INF_B)


flu[is.na(flu)] <- 0
```

```{r}
q<-flu %>%
  group_by(ISO_WEEKSTARTDATE) %>%
  summarise(INF_A = sum(INF_A), INF_B = sum(INF_B))
cor(q$INF_A,q$INF_B)
```

```{r}
flu |>group_by(ISO_WEEKSTARTDATE)%>%
  summarise(INF_A=sum(INF_A),INF_B=sum(INF_B))|>
  ggplot() +
  aes(x = INF_A,
      y = INF_B) +
  geom_point() +
  geom_smooth(method = "lm", formula = 'y ~ x')+
  annotation_logticks(sides = "l") +
  scale_y_continuous(trans = "pseudo_log")

```

```{r}
flu<-flu|>mutate(month=month(ISO_WEEKSTARTDATE))|>relocate(month)
flu <- flu %>%
  mutate(winter_seasion = case_when(
    (HEMISPHERE=="NH" & month %in% c(12,1,2) ) ~ TRUE,
    (HEMISPHERE=="SH" & month %in% c(6,7,8) ) ~ TRUE,
    # Add more conditions as needed
    TRUE ~ FALSE
  ))
flu|>
  group_by(WHOREGION)|>summarise(percentage=sum(winter_seasion)/n())|>
  arrange(desc(percentage))
```

```{r}
flu_long <- flu %>%
  pivot_longer(cols = c(INF_A, INF_B), names_to = "Infection_Type", values_to = "Infection_Count")

# Create a box plot with log scale for y-axis
ggplot(flu_long, aes(x = Infection_Type, y = Infection_Count)) +
  geom_boxplot(fill = "skyblue", color = "darkblue") +
  labs(title = "Distribution of Infection Numbers (log scale)", x = "Infection Type",y = expression(paste("Infection Count  ", 10^-3 ))) +
  scale_y_log10() +  # Use log scale for y-axis
  theme_minimal()

```

```{r}
summary_flu<-flu |>
  group_by(year=ISO_YEAR)%>%
  summarise(s=sum(SPEC_PROCESSED_NB))

ggplot(summary_flu, aes(x = year, y = s)) + 
  geom_bar(stat = "sum", fill = "blue") +
  labs(title = "Number of tested patients Per Three Years",
       x = "Year",
       y = "Number of tested patients") +
  theme_minimal()+
  scale_y_continuous(labels = scales::comma_format())
```

```{r}
install.packages("gganimate")
library(gganimate)
flu$ISO_YEAR <- as.numeric(as.character(flu$ISO_YEAR))

summary_flu <- flu %>%
  group_by(year = ISO_YEAR) %>%
  summarise(s = sum(SPEC_PROCESSED_NB))

# Create an animated line chart
p <- ggplot(summary_flu, aes(x = year, y = s)) +
  geom_bar(stat = "sum", fill = "blue") +
  labs(title = "Number of tested patients Per Three Years",
       x = "Year",
       y = "Number of tested patients") +
  theme_minimal() +
  scale_y_continuous(labels = scales::comma_format()) +
  transition_states(year, transition_length = 1, state_length = 1)

# Animate the ggplot
anim <- animate(p, nframes = length(unique(summary_flu$year)))

anim
```

```{r}
x<-flu|> group_by(ISO_YEAR)|>
  summarise(INF_ALL=sum(INF_ALL),HUMAN_CORONA=sum(HUMAN_CORONA),
            METAPNEUMO=sum(METAPNEUMO),PARAINFLUENZA=sum(PARAINFLUENZA),
            RHINO=sum(RHINO),RSV=sum(RSV))

x$ISO_YEAR <- as.numeric(as.character(x$ISO_YEAR))



gathered_data <- x %>%
  gather(variable, value, INF_ALL, HUMAN_CORONA,METAPNEUMO,PARAINFLUENZA,
         RHINO,RSV)

# Create a line chart
ggplot(gathered_data, aes(x = ISO_YEAR, y = value, color = variable)) +
  geom_line() +
  labs(title = "Time Series of Variables", y = "Value") +
  scale_color_manual(values = c(
    "INF_ALL" = "red", 
    "HUMAN_CORONA" = "blue", 
    "METAPNEUMO" = "green", 
    "PARAINFLUENZA" = "purple", 
    "RHINO" = "orange", 
    "RSV" = "brown"
  )) +
  
  theme_minimal()
```

```{r}
gathered_data <- x %>%
  gather(variable, value, HUMAN_CORONA,METAPNEUMO,PARAINFLUENZA,
         RHINO,RSV)

# Create a line chart
ggplot(gathered_data, aes(x = ISO_YEAR, y = value, color = variable)) +
  geom_line() +
  labs(title = "Time Series of Variables", y = "Value") +
  scale_color_manual(values = c(
    "HUMAN_CORONA" = "blue", 
    "METAPNEUMO" = "green", 
    "PARAINFLUENZA" = "purple", 
    "RHINO" = "orange", 
    "RSV" = "brown"
  )) +
  theme_minimal()
```

```{r}
gathered_data <- x %>%
  gather(variable, value, HUMAN_CORONA,METAPNEUMO,PARAINFLUENZA,
         RHINO)

# Create a line chart
ggplot(gathered_data, aes(x = ISO_YEAR, y = value, color = variable)) +
  geom_line() +
  labs(title = "Time Series of Variables", y = "Value") +
  scale_color_manual(values = c(
    "HUMAN_CORONA" = "blue", 
    "METAPNEUMO" = "green", 
    "PARAINFLUENZA" = "purple", 
    "RHINO" = "orange"
  )) +
  theme_minimal()
```

```{r}
y <- flu %>%
  summarise(INF_A = sum(INF_A), INF_B = sum(INF_B))

total <- sum(y)
percentage_data <- y / total * 100



# Create a pie chart
pie(unlist(percentage_data), labels = paste0(names(percentage_data), ": ", round(percentage_data, 1), "%"), col = rainbow(length(y)))

# Add a legend
legend("topright", legend = names(y), fill = rainbow(length(y)))
```



```{r}
z<-flu|>group_by(WHOREGION)|>summarise(s=sum(INF_ALL))

z <- mutate(z, percentage = s / sum(s) * 100)

# Create a horizontal bar chart
plot2<-ggplot(z, aes(x = percentage, y = fct_reorder(WHOREGION, -percentage))) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Percentage of Each WHO Region",
       x = "Percentage",
       y = "WHO Region") +
  xlab("WHOREGION") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
plot2 +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), vjust = -0.5, size = 4)
```

